# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huGjHYsrx9_OYy7wEDNhtR6dT4KWuIjr
"""

#TO PRINT FIBONNACI SEQUENCE
n = int(input("Enter a number:\n"))
i = 1
a = 0
b = 1
while i<=n:
    print(a)
    a,b=b,a+b
    i += 1